### ISSUE TITLE
Update and create working skeleton of the app

### ISSUE THREAD

**Issue by nwrighteous** [nuvention-web/Team-D#8]
## Low-priority basics for the user

**Enhancements**:
- Build a login screen - perhaps a modal
- Hamburger nav menu
- Basic user account settings (name, email, password, time zone)

**Test criteria**:
- Ability to log in
- Navigating hamburger menu
- Modals that don't take the user away from the previous screen
- More TBD

**Comment by megancon** [comment]
skeleton:
OVERALL VIEW [See total engagement, demographics, devices, etc. of all platforms] 
---------->  VIEW BY PLATFORM [Tab between Facebook, Youtube, Ooyala to see performance]
-----------------------------> VIEW BY VIDEO [Drill into specific videos and get deeper analytics]
